name: ClientManagerApp Android Release

on:
  push:
    branches: [ master ]
    tags:
    - 'test'
jobs:
  version:
    name: Create version number
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune --depth=10000
        
  build:
    name: Build APK and Create release
    needs: [ version ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.0'
    - run: flutter pub get
  #- run: flutter test
    - run: flutter build apk
  # - run: flutter build appbundle
# Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: ClientManagerApp
        path: build/app/outputs/apk/release/app-release.apk
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      with:
        tag_name: release-${{github.run_id}}
        release_name: Release-${{github.run_id}}
        body: |
            Funcionalidades del release:
            - Notificaciones de cobros por realizar
            - Configuraciones de cuentas, backups,pin
            - Registro de clientes
            - Autenticaci√≥n
        draft: false
        prerelease: false
